"*.{json,yml}":
  - prettier --ignore-unknown --write

"*.ts":
  - prettier --ignore-unknown --write
  - pnpm run generate-eslintrc
  - eslint --fix
  - cspell

"*.md":
  - prettier --ignore-unknown --write
  - markdownlint --config=.markdownlint.json --ignore-path=.markdownlintignore
  - cspell
