language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "12"
before_script:
script:
  - yarn lint
  - yarn test
after_success:
  - yarn report-coverage
