import type { Linter } from "eslint";

export const rules: Linter.Config["rules"] = {
  "for-direction": "error",
  "getter-return": "error",
  "no-await-in-loop": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": ["error", "always"],
  "no-console": "off",
  "no-constant-condition": "error",
  "no-control-regex": "error",
  "no-debugger": "warn",
  "no-dupe-args": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty": ["warn", { allowEmptyCatch: true }],
  "no-empty-character-class": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-parens": [
    "error",
    "all",
    {
      nestedBinaryExpressions: false,
    },
  ],
  "no-extra-semi": "error",
  "no-func-assign": "error",
  "no-inner-declarations": ["error", "functions"],
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-misleading-character-class": "error",
  "no-obj-calls": "error",
  "no-prototype-builtins": "error",
  "no-regex-spaces": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "warn",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "require-atomic-updates": "error",
  "use-isnan": "error",
  "valid-typeof": [
    "error",
    {
      requireStringLiterals: true,
    },
  ],
};
