import { type Linter } from "eslint";

export const settings: Linter.Config = {
  plugins: ["markdown"],

  extends: ["plugin:markdown/recommended"],

  overrides: [
    {
      files: ["./**/*.md"],
      processor: "markdown/markdown",
    },
    {
      files: ["./**/*.md/**"],
      parserOptions: {
        project: null,
      },
      extends: [
        "plugin:markdown/recommended",
        "plugin:@typescript-eslint/disable-type-checked",
        "plugin:functional/off",
      ],
      rules: {
        "@typescript-eslint/consistent-generic-constructors": "off",
        "@typescript-eslint/consistent-type-definitions": "off",
        "@typescript-eslint/explicit-member-accessibility": "off",
        "@typescript-eslint/no-empty-function": "off",
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-unused-expressions": "off",
        "@typescript-eslint/no-unused-vars": "off",
        "@typescript-eslint/prefer-function-type": "off",
        "dot-notation": "off",
        "import/extensions": "off",
        "import/newline-after-import": "off",
        "import/no-unresolved": "off",
        "init-declarations": "off",
        "jsdoc/require-jsdoc": "off",
        "n/handle-callback-err": "off",
        "no-alert": "off",
        "no-console": "off",
        "no-empty-function": "off",
        "no-empty": "off",
        "no-invalid-this": "off",
        "no-labels": "off",
        "no-lone-blocks": "off",
        "no-restricted-syntax": "off",
        "no-throw-literal": "off",
        "no-undef": "off",
        "no-unused-expressions": "off",
        "no-unused-labels": "off",
        "no-unused-vars": "off",
        "no-useless-return": "off",
        "node/prefer-global/process": "off",
        "prefer-const": "off",
        "prettier/prettier": "off",
        "sonarjs/no-extra-arguments": "off",
        "sonarjs/no-unused-collection": "off",
        "style/comma-dangle": "off",
        "style/eol-last": "off",
        "ts/consistent-type-imports": "off",
        "ts/no-namespace": "off",
        "ts/no-redeclare": "off",
        "ts/no-require-imports": "off",
        "ts/no-unused-vars": "off",
        "ts/no-use-before-define": "off",
        "ts/no-var-requires": "off",
        "unicode-bom": "off",
        "unicorn/prefer-optional-catch-binding": "off",
        "unicorn/prefer-top-level-await": "off",
        "unicorn/switch-case-braces": "off",
        "unused-imports/no-unused-imports": "off",
        "unused-imports/no-unused-vars": "off",
      },
    },
  ],
};
