name: Lint with ESLint

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  lint_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run typegen
      - run: pnpm run lint:eslint
