name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Install Dependencies
        run: yarn install
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Setup git
        run: |
          git config user.name "Release Bot"
          git config user.email noreply@github.com

      # Publish to NPMJS
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org/"
      - name: Publish to NPMJS
        id: semantic
        uses: codfish/semantic-release-action@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to GitHub Package Registry
      - if: steps.semantic.outputs.new-release-published == 'true'
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Package Registry
        if: steps.semantic.outputs.new-release-published == 'true'
        run: yarn publish --non-interactive --new-version=${{ steps.semantic.outputs.release-version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
